openapi: 3.1.0
info:
  title: Hello service
  version: 1.0.0
  description: Example for a service
servers:
  - url: https://localhost:5000
paths:
  /api/1.0/ping:
    get:
      summary: Ping
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string

  /api/1.0/definition:
    get:
      summary: Get definition
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object

  /api/1.0/info:
    get:
      summary: Get info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  project:
                    type: string
                  version:
                    type: string
                  service:
                    type: string
                  language:
                    type: string
                  type:
                    type: string
                  date:
                    type: string

  /api/1.0/predict:
    post:
      operationId: predict
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Input"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Output"

components:
  schemas:
    Input:
      type: object
      properties:
        sequence:
          type: "string"
          description: "The sequence to be predicted"
        labels:
          type: "string"
          description: "The labels to be predicted"
    Output:
      type: object
      properties:
        labels:
          type: "array"
          items:
            type: "string"
        scores:
          type: "array"
          items:
            type: "number"
        sequence:
          type: "string"
          description: "The sequence to be predicted"